### ISSUE TITLE
can we say PM is better than BT?

### ISSUE THREAD

**Issue by yechenzhi** [RLHFlow/RLHF-Reward-Modeling#12]
from your [paper](https://arxiv.org/pdf/2405.07863)  table 2 and from the [benchmark](https://huggingface.co/spaces/allenai/reward-bench), we can see PM's result is better than Bradley-Terry's, so can we claim PM is a better modeling method? And is there any work to explain this?

**Comment by WeiXiongUST** [comment]
Mathematically, the general pair-wise preference model is a class with larger capacity than the BT model (as BT model is a special case). So the best pair-wise preference model must be better than BT model. 

However, in practice, as the modeling is confined to the optimization error, and finite data, the claim should be more careful. But we have seen that the 0.4B llm-blender/PairRM (pair preference model) is pretty good and the PM is promising as evaluated by reward benchmark, especially in the reasoning task. I would say that the PM is promising if you only need ranking information (like RAFT and iterative DPO/IPO/Slic). But we may need more experiments to determine whether PM is strictly better.
