### ISSUE TITLE
How to calculate the avg score of reward bench?

### ISSUE THREAD

**Issue by eyuansu62** [RLHFlow/RLHF-Reward-Modeling#14]
So that we can match the rank of reward bench.

**Comment by WeiXiongUST** [comment]
For Chat & Chat-hard & Reasoning & Safety, I believe that it should be average with equal weights. But you may also need to compute the prior set by the code of reward bench... 

My suggestion is that if you find your model is good with respect to the previous 4 metrics, you can crate a PR at reward bench to ask the authors' help.

**Comment by eyuansu62** [comment]
Thanks for your help!
