### ISSUE TITLE
Code for Armo on Reward Bench

### ISSUE THREAD

**Issue by philschmid** [RLHFlow/RLHF-Reward-Modeling#15]
Hello, i am curious if you plan to add code in https://github.com/RLHFlow/RLHF-Reward-Modeling/tree/main/useful_code for how you run the ARMO model for Reward Bench.

**Comment by WeiXiongUST** [comment]
@Haoxiang-Wang hi haoxiang, could you look into this?

**Comment by Haoxiang-Wang** [comment]
Hi @philschmid 

For ArmoRM evaluation on RewardBench, I directly pushed an eval code to RewardBench, and you can check out the evaluation command at this PR: https://github.com/allenai/reward-bench/pull/135

**Comment by philschmid** [comment]
Hey thank you for sharing i opened a PR on your model card to make the usage for non expert a bit easier based on your Reward Bench PR, which uses  the preference score for the response, aggregated from the  multi-objective rewards with the gating layer.



https://huggingface.co/RLHFlow/ArmoRM-Llama3-8B-v0.1/discussions/3

**Comment by Haoxiang-Wang** [comment]
Thank you @philschmid for the new usage demo code!
I just updated the READMEs of our HuggingFace page and this repo (see https://github.com/RLHFlow/RLHF-Reward-Modeling/commit/15226e9090d8d941b4b324fabfe5d6a780406290)
