### ISSUE TITLE
tutorial to reproduce ArmoRM

### ISSUE THREAD

**Issue by pluiez** [RLHFlow/RLHF-Reward-Modeling#17]
Hi, would you release a readme on how to reproduce ArmoRM training procedure?

**Comment by Haoxiang-Wang** [comment]
We just released the tech report at: https://arxiv.org/abs/2406.12845
Code tutorial will be released next month

**Comment by halfrot** [comment]
@Haoxiang-Wang Hi, any updates on the training code tutorial?
