### ISSUE TITLE
preference_700K dataset's  details?

### ISSUE THREAD

**Issue by yechenzhi** [RLHFlow/RLHF-Reward-Modeling#19]
Hi, how do you get hendrydong/preference_700K dataset? There is no information in the dataset card.

**Comment by WeiXiongUST** [comment]
You can check our technical report for the details https://arxiv.org/pdf/2405.07863 

Also, we have preprocessed these datasets and uploaded them here https://huggingface.co/collections/RLHFlow/standard-format-preference-dataset-662eec0252e194d5d40c252a , where the script is associated with the datasets.

**Comment by yechenzhi** [comment]
Thanks for your reply, but I can't find the script for [preference_700K](https://huggingface.co/datasets/hendrydong/preference_700K), can you help me to check if the script is uploaded?

**Comment by WeiXiongUST** [comment]
Unfortunately, the dataset was processed in an early stage where this project was just a course project... Therefore, the processing is not appropriately recorded. You may merge the standard datasets by yourself instead.

**Comment by yechenzhi** [comment]
Ok, thanks!
