### ISSUE TITLE
Cannot run the training script

### ISSUE THREAD

**Issue by peter-peng-w** [RLHFlow/RLHF-Reward-Modeling#2]
Thank you for sharing your scripts for training reward models based on mistral-7b and gemma-2b! **May I ask which version of transformers and accelerate are you using?** I followed the instruction and built the environment from [alignment-handbook](https://github.com/huggingface/alignment-handbook). However, when I use their latest version (transformers==4.39.0 and accelerate=0.27.2), I keep getting the following errors when using deepspeed
```
ValueError: DeepSpeed Zero-3 is not compatible with `low_cpu_mem_usage=True` or with passing a `device_map`.
```
But in the training script we didn't set `device_map` so it should be `None`.

And when running the script without deepspeed, I got another error:
```
File "/p/anaconda3/envs/reward-model/lib/python3.10/site-packages/accelerate/utils/dataclasses.py", line 1061, in set_auto_wrap_policy
    raise Exception("Could not find the transformer layer class to wrap in the model.")
```
Both errors will gone once I switch the transformers library back to 4.36.2 and accelerate library back to 0.23.0 (which are used by alignment-handbook before Mar 1st, 2024). But in this case transformers won't support gemma...

**Comment by WeiXiongUST** [comment]
Hi thanks for your interests! It seems that the trl has been updated a lot since then. Could you try the following branch to install the alignment handbook?

```sh
conda create -n handbook python=3.10.9
conda activate handbook
pip3 install torch==2.1.2 torchvision torchaudio
git clone https://github.com/huggingface/alignment-handbook.git
git checkout d17fd7cd3b71c6a7bf7af34d8dc73135bb7ea8e9
python -m pip install .
python -m pip install flash-attn==2.3.6 --no-build-isolation
```
