### ISSUE TITLE
Code to reproduce ArmoRM

### ISSUE THREAD

**Issue by halfrot** [RLHFlow/RLHF-Reward-Modeling#28]
Hi, this is great work and I'd like to know if there is a plan to release the training code to reproduce the model?

**Comment by Haoxiang-Wang** [comment]
Sorry for the delay. I try to release it this month.

**Comment by teixeira-neospace** [comment]
what about the moe for the calculation of the coefficients?

**Comment by Haoxiang-Wang** [comment]
Will release the code this week!

**Comment by vincezh2000** [comment]
Hi, Haoxiang, when will the code for ArmoRM be released?

**Comment by Haoxiang-Wang** [comment]
Code released!
