### ISSUE TITLE
preference dataset 404 not found

### ISSUE THREAD

**Issue by wty500** [RLHFlow/RLHF-Reward-Modeling#29]
> We preprocess many open-source preference datasets into the standard format and upload them to the hugginface hub. You can find them [HERE](https://huggingface.co/collections/RLHFlow/standard-format-preference-dataset-662eec0252e194d5d40c252a). We have also searched and founda that some of the following mixture of preference dataset useful.
>
>    [weqweasdas/preference_dataset_mix2](https://github.com/RLHFlow/RLHF-Reward-Modeling/blob/main/weqweasdas/preference_dataset_mix2)
>    [weqweasdas/preference_dataset_mixture2_and_safe_pku](https://github.com/RLHFlow/RLHF-Reward-Modeling/blob/main/weqweasdas/preference_dataset_mixture2_and_safe_pku)
>    [hendrydong/preference_700K](https://huggingface.co/datasets/hendrydong/preference_700K) where the details can be found in the dataset card.

These urls in README.md direct to a page not found.

---

By the way, the evaluation command
```
CUDA_VISIBLE_DEVICES=1 python ./useful_code/eval_reward_bench_bt.py --reward_name_or_path ./models/gemma_2b_mixture2_last_checkpoint --record_dir ./bench_mark_eval.txt
```
will yield
```
OSError: Incorrect path_or_model_id: './models/gemma_2b_mixture2_last_checkpoint'. Please provide either the path to a local folder or the repo_id of a model on the Hub.
```
and I am having trouble in installing `./models/gemma_2b_mixture2_last_checkpoint`, since there is no such guide on its installation.

**Comment by WeiXiongUST** [comment]
Thanks for bringing this to us.

You can use https://huggingface.co/datasets/hendrydong/preference_700K, which is the final mixture we use.

For ./models/gemma_2b_mixture2_last_checkpoint, it is a model address that you have saved your own model. If you want to test the evaluation process, you can try the model I upload to the hugginface: weqweasdas/RM-Gemma-2B

**Comment by wty500** [comment]
It helps a lot. Thank you!
