### ISSUE TITLE
reproduce ArmoRM

### ISSUE THREAD

**Issue by richhh520** [RLHFlow/RLHF-Reward-Modeling#30]
Hi,

I'm looking forward to reproducing ArmoRM. Will the code be released soon?

Thanks!!

**Comment by Haoxiang-Wang** [comment]
Will release code this week!

**Comment by ashes1106** [comment]
Hi, look forward to reproducing ArmoRM, too.

**Comment by Haoxiang-Wang** [comment]
Code released!
