### ISSUE TITLE
ArmoRM-Llama3-8B-v0.1's tokenizer is different from Meta-Llama-3-8B-Instruct's 

### ISSUE THREAD

**Issue by efsotr** [RLHFlow/RLHF-Reward-Modeling#32]

**Comment by Haoxiang-Wang** [comment]
Could you give more details?

**Comment by efsotr** [comment]
https://huggingface.co/RLHFlow/ArmoRM-Llama3-8B-v0.1/blob/main/tokenizer.json and 
https://huggingface.co/meta-llama/Meta-Llama-3-8B/blob/main/tokenizer.json
are different.

**Comment by efsotr** [comment]
diff result:

2309,2317d2308
<     },
<     {
<       "id": 128256,
<       "content": "[PAD]",
<       "single_word": false,
<       "lstrip": false,
<       "rstrip": false,
<       "normalized": false,
<       "special": true
2341,2344c2332,2394
<     "type": "ByteLevel",
<     "add_prefix_space": true,
<     "trim_offsets": false,
<     "use_regex": true
---
>     "type": "Sequence",
>     "processors": [
>       {
>         "type": "ByteLevel",
>         "add_prefix_space": true,
>         "trim_offsets": false,
>         "use_regex": true
>       },
>       {
>         "type": "TemplateProcessing",
>         "single": [
>           {
>             "SpecialToken": {
>               "id": "<|begin_of_text|>",
>               "type_id": 0
>             }
>           },
>           {
>             "Sequence": {
>               "id": "A",
>               "type_id": 0
>             }
>           }
>         ],
>         "pair": [
>           {
>             "SpecialToken": {
>               "id": "<|begin_of_text|>",
>               "type_id": 0
>             }
>           },
>           {
>             "Sequence": {
>               "id": "A",
>               "type_id": 0
>             }
>           },
>           {
>             "SpecialToken": {
>               "id": "<|begin_of_text|>",
>               "type_id": 1
>             }
>           },
>           {
>             "Sequence": {
>               "id": "B",
>               "type_id": 1
>             }
>           }
>         ],
>         "special_tokens": {
>           "<|begin_of_text|>": {
>             "id": "<|begin_of_text|>",
>             "ids": [
>               128000
>             ],
>             "tokens": [
>               "<|begin_of_text|>"
>             ]
>           }
>         }
>       }
>     ]
2360c2410
<     "ignore_merges": false,
---
>     "ignore_merges": true,

**Comment by Haoxiang-Wang** [comment]
The base model is https://huggingface.co/sfairXC/FsfairX-LLaMA3-RM-v0.1 and we adopted its tokenizer. 
Maybe @hendrydong can answer this question.

**Comment by hendrydong** [comment]
I think the main reason is that we added a special token for padding. Just like  https://github.com/RLHFlow/RLHF-Reward-Modeling/blob/86e08cde705e3743962254993152d181bbf12e3d/bradley-terry-rm/llama3_8B_rm.py#L113 
`tokenizer.add_special_tokens({'pad_token': '[PAD]'})`. Using eos for padding may cause some issues for multi-round conversations.

**Comment by efsotr** [comment]
```python
from transformers import AutoTokenizer

t = AutoTokenizer.from_pretrained("Meta-Llama-3-8B-Instruct")
t1 = AutoTokenizer.from_pretrained("ArmoRM-Llama3-8B-v0.1-old")
r = "<|end_of_text|> thỏa"
r0 = t.encode(r, add_special_tokens=False)
r1 = t1.encode(r, add_special_tokens=False)
r0, r1
```

```txt
([128001, 121167], [128001, 270, 86242, 64])
```

**Comment by hendrydong** [comment]
Hi, I think this is because that early versions of tokenizer does not support some features, e.g., "ignore_merges", which has also been mentioned other repos (https://huggingface.co/meta-llama/Meta-Llama-3-70B-Instruct/discussions/21 and  
 https://github.com/huggingface/tokenizers/issues/1537).

Note that this does not influence the encoder-decoder process.  For example, `t.decode(r0) == t1.decode(r1) == t.decode(r1) == t1.decode(r0)` is `True`. Only for some rare tokens, it may have some impacts. It should be okay for general usecases.
