### ISSUE TITLE
KeyError: 'input_ids_j' in training

### ISSUE THREAD

**Issue by iseesaw** [RLHFlow/RLHF-Reward-Modeling#6]
Thanks for your wonderful project!

I got an error during training with custom dataset:

```
 11%|██████████████                                                     | 125/1125 [1:04:25<8:30:35, 30.64s/it]
Traceback (most recent call last):
    "input_ids": feature["input_ids_j"],    "input_ids": feature["input_ids_j"],

KeyErrorKeyError: : 'input_ids_j'
```

There is no empty value in my chosen and rejected data. I don't understand why it happens.

**Comment by WeiXiongUST** [comment]
In build_dataset(tokenizer, train_path, eval_path) and ds = ds.map(tokenize, num_proc=8), we should add the feature 'input_ids_j' for each sample. Can you provide a minimal script to reproduce the error?

**Comment by iseesaw** [comment]
Sorry, I noticed that the passed independent validation data was not properly processed .

Solved. Thank you again.
