### ISSUE TITLE
Does pair-pm supports multi-turn conversation?

### ISSUE THREAD

**Issue by heyzude** [RLHFlow/RLHF-Reward-Modeling#9]
Was pair-pm trained on multi-turn conversations too?

Thanks!

**Comment by WeiXiongUST** [comment]
yes, as you can see, pair-rm achieves ~72 test accuracy in hh-rlhf, which is a multi-turn conversion. All you need to do is to pre-process the sample into the standard format 

```python
choose = [
{ "content": "Please identify the top 5 rarest animals in the world.", "role": "user" },
{ "content": "Do you mean animals that are really rare, or rare relative to the size of the human population?", "role": "assistant" },
{ "content": "The ones that are really rare.", "role": "user" },
{ "content": "Alright, here’s what I found:", "role": "assistant" }, 
]
```

rejected is preprocessed similarly and they are only different in the last round of conversation. And then we can get the context and responses as follows.

```python
context = self.tokenizer_data_format.apply_chat_template(chosen[:-1], tokenize=False)
responses = [chosen[-1]["content"], rejected[-1]["content"]]
```

**Comment by heyzude** [comment]
Thank you so much! 
I appreciate it :)
